USE ecommerce_interview;
# Q31. Display all orders along with customer names.
with all_orders_customer as (select c.customer_name,o.order_id,o.customer_id,o.order_date,o.status,o.payment_method 
from customers as c
join orders as o
on c.customer_id=o.customer_id)
select status, count(status) as status_count
from all_orders_customer
group by status
order by status_count desc;
# Q32. Find total revenue generated by each customer.
select c.customer_name,sum(oi.unit_price*oi.quantity) as total_revenue
from customers as c
join orders as o
on c.customer_id=o.customer_id
join order_items as oi
on o.order_id=oi.order_id
group by c.customer_name, c.customer_id;
# Q33. Find the total number of orders placed by each customer.
select c.customer_name, count(o.order_id) as order_count
from customers as c
join orders as o
on o.customer_id=c.customer_id
group by c.customer_name,c.customer_id;
# Q34. Find customers who never placed any orders.
select c.customer_name,o.order_id
from customers as c
left join orders as o
on c.customer_id=o.customer_id
where o.order_id is NULL;
# Q35. Find the latest order date for each customer.
select c.customer_name, max(o.order_date) as latest_order
from customers as c
join orders as o
on c.customer_id=o.customer_id
group by c.customer_name, c.customer_id;
# Q36. Find product-wise revenue generated.
select p.product_name,sum(oi.unit_price*oi.quantity) as revenue
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name;
# Q37. Find products that were never sold.
select p.product_name,count(oi.quantity) as quantity_sold
from products as p
left join order_items as oi
on p.product_id=oi.product_id
group by p.product_name
having quantity_sold=0;
# Q38. Find products whose stock is lower than the total quantity sold.
select p.product_name,p.stock, sum(oi.quantity) as total_quantity
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name,p.stock
having p.stock<sum(oi.quantity);
# Q39. Find category-wise revenue contribution percentage.
select p.category,( sum(oi.unit_price*oi.quantity) /( select sum(unit_price*quantity) 
as company_revenue from order_items))* 100 as percentage_contribution
from products as p
join order_items as oi
on p.product_id =oi.product_id
group by p.category;

# Q40. Find repeat customers who ordered in multiple months.
select c.customer_name, count(distinct date_format(order_date,"%Y-%M")) as active_customers 
from orders as o
join customers as c
on c.customer_id=o.customer_id
group by c.customer_name
having active_customers>1
order by active_customers desc;

# Q41. Calculate overall company revenue.
select sum(unit_price*quantity) as total_revenue
from order_items;
# Q42. Calculate average order value.
with average_order as (select order_id,sum(unit_price*quantity) as total_revenue
from order_items
group by order_id)
select avg(total_revenue) from average_order;
# Q43. Calculate cancelled order percentage.
select round((count(order_id) /(select count(order_id) from orders)*100),2) as cancelled_percentage
from orders
where status="cancelled";
# Q44. Find the month with highest revenue.
select date_format(o.order_date,"%Y-%M") as month, sum(oi.unit_price*oi.quantity) as total_revenue
from orders as o
join order_items as oi
on o.order_id=oi.order_id
group by month
order by total_revenue desc
limit 1;
# Q45. Find the month with highest order volume.
select date_format(order_date, '%Y-%M') as month, count(order_id) as order_volume
from orders 
group by month
order by order_volume desc
limit 1;

# Q46. Find the most common order status.
select status,count(status) as common_status from orders
group by status
order by common_status desc
limit 1;
# Q47. Generate a payment-method-wise revenue report.
select o.payment_method, sum(oi.unit_price*oi.quantity) as revenue
from orders as o
join order_items as oi
on o.order_id=oi.order_id
group by o.payment_method
order by revenue desc;
# Q48. Generate a category-wise business summary report.
select p.category, sum(oi.unit_price*oi.quantity) as total_revenue, sum(oi.quantity) as total_quantity, count(distinct oi.order_id) as order_count
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.category;
# Q49. Generate a city-wise customer and revenue report.
select c.city, count(distinct c.customer_name) as customer_count, sum(oi.unit_price*oi.quantity) as revenue
from customers as c
join orders as o
on c.customer_id=o.customer_id
join order_items as oi
on o.order_id=oi.order_id
group by c.city
order by revenue desc;
# Q50. Generate a final executive sales report containing:
select c.customer_name,
p.product_name,
p.Category,
oi.Quantity,
oi.unit_Price,
(oi.unit_price*oi.quantity) as Revenue,
o.Order_Date,
o.Status,
o.Payment_Method,
C.City from customers as c
join orders as o
on c.customer_id=o.customer_id
join order_items as oi
on o.order_id=oi.order_id
join products as p
on p.product_id=oi.product_id;

