CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

select * from customers;
# Q1. Show all customers from Bengaluru.
select * from customers
where city="Bengaluru";
# Q2. Show customers who signed up after ‘2025-01-01’.
select * from customers
where signup_date>"2024-01-01";
# Q3. Find customers from Mumbai and Hyderabad.
select * from customers
where city in ( "Bengaluru","Hyderabad"); 
select * from products;
# Q4. Show products belonging to the Electronics category.
select product_name from products
where category="Electronics";
# Q5. Find products priced above 40000.
select product_name from products
where price> 40000;
# Q6. Show products where stock is less than 20.
select product_name from products
where stock<20;
# Q7. Find products with stock between 50 and 100.
select product_name from products
where stock between 50 and 100;
# Q8. Show customers whose names start with ‘A’.
select customer_name from customers
where customer_name like "A%";
# Q9. Find products whose names contain ‘Premium’.
select product_name from products
where product_name like "premium%";
# Q10. Show customers registered during the year 2025.
select * from customers
where year(signup_date)="2025";

select * from order_items;
select * from orders;
# Q11. Find total revenue generated by each category.
select p.category, sum(oi.unit_price * oi.quantity) as revenue
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.category
order by revenue desc;

# Q12. Find total quantity sold for each product.
select p.product_name, sum(oi.quantity) as total_quantity 
from order_items as oi
join products as p
on oi.product_id=p.product_id
group by p.product_name;
# Q13. Find total orders under each order status.
select status, count(order_id) as total_orders from orders
group by status;
# Q14. Find total revenue generated through each payment method.
select o.payment_method, sum(oi.unit_price * oi.quantity) as total_revenue 
from orders as o
join order_items as oi
on o.order_id=oi.order_id
group by o.payment_method
order by total_revenue desc;
# Q15. Find average product price category-wise.
select category, avg(price) as avg_price
from products
group by category;
# Q16. Find category-wise quantity sold.
select p.category, sum(oi.quantity) as total_quantity
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.category;
# Q17. Find monthly order count.
select date_format(order_date,"%Y-%M") as months, count(order_id) as order_count
from orders
group by months
order by months;
# Q18. Find monthly revenue trend.
select date_format(o.order_date,"%Y-%M") as months, sum(oi.unit_price*oi.quantity) as total_revenue
from order_items as oi
join orders as o
on o.order_id=oi.product_id
group by months
order by months;
# Q19. Find the most commonly used payment method.
select payment_method, count(payment_method) as method_count
from orders
group by payment_method
order by method_count
limit 1;
# Q20. Find the highest revenue-generating category.
select p.category, sum(oi.unit_price * oi.quantity) as total_revenue
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.category
order by total_revenue desc
limit 1;
# Q21. Find customers who placed more than 5 orders.
select c.customer_name,count(o.order_id) as order_count
from customers as c
join orders as o
on c.customer_id=o.customer_id
group by c.customer_name, c.customer_id
having count(o.order_id)>5;
# Q22. Find top 5 customers based on total spending.
select c.customer_name,sum(oi.unit_price*oi.quantity) as total_spending
from customers as c
join orders as o
on c.customer_id=o.customer_id
join order_items as oi
on o.order_id=oi.order_id
group by c.customer_name,c.customer_id
order by total_spending desc
limit 5;
# Q23. Find products sold more than 30 times.
select p.product_name, sum(oi.quantity) as sold_quantity
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name
having sum(oi.quantity) >30
order by sold_quantity desc;

# Q24. Find categories generating revenue greater than 500000.
select category, sum(price) as revenue
from products
group by category
having sum(price) >500000;

# Q25. Find cities having more than 10 customers.
select city, count(customer_name) as customer_count
from customers
group by city
having customer_count >10;
# Q26. Find the top 5 highest-selling products.
select p.product_name, sum(oi.quantity) as sold_quantity
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name
order by sold_quantity desc
limit 5;
# Q27. Find the top 3 most profitable products.
select p.product_name, sum(oi.unit_price*oi.quantity) as profit
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name
order by profit desc
limit 3;
# Q28. Find customers whose spending is above average customer spending.
with spending as (select c.customer_name,sum(oi.unit_price*oi.quantity) as total_spending
from customers as c
join orders as o
on c.customer_id=o.customer_id
join order_items as oi
on o.order_id=oi.order_id
group by c.customer_name,c.customer_id)
select * from spending where total_spending > (select avg(total_spending) from spending);

# Q29. Find products contributing more than 10% of company revenue.
select p.product_name, sum(oi.unit_price*oi.quantity) as total_revenue
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name
having total_revenue >(0.10*(select sum(unit_price*quantity) as company_revenue from order_items));

# Q30. Find the city generating the highest revenue.
select c.city, sum(p.price) as total_revenue
from customers as c
join products as p
on c.customer_id=p.product_id
group by c.city
order by total_revenue desc
limit 1;



